import { test, expect } from '@playwright/test';
import { signInGoogle } from './auth-helper';
test.beforeEach(() => {
  if (process.env.E2E_FIREBASE !== 'true') throw new Error('Use the isolated Firebase test runner.');
});
test('public landing and protected deep links never read placement documents before sign-in', async ({ page }) => {
  const reads: string[] = [];
  page.on('request', request => { if (request.url().includes(':8080')) reads.push(request.url()); });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: /Your placement prep/ })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Continue with Google' })).toBeEnabled();
  await expect(page.getByRole('textbox')).toHaveCount(0);
  await page.goto('/#2025/company/google');
  await expect(page.getByRole('heading', { name: 'Good to see you.' })).toBeVisible();
  await expect(page.getByText(/take you back to the page/)).toBeVisible();
  expect(reads).toEqual([]);
  await signInGoogle(page, false);
  await expect(page).toHaveURL(/#2025\/company\/google$/);
  await expect(page.getByRole('heading', { name: 'Google', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Google', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('main navigation has two areas, company stats own contacts, and account owns contributions; logout closes access', async ({ page }) => {
  await signInGoogle(page);
  await expect(page.getByRole('heading', { name: 'Welcome, Test.' })).toBeVisible();
  for (const year of [2027,2026,2025]) await expect(page.getByRole('heading', { name: `Class of ${year}`, exact: true })).toBeVisible();
  await page.screenshot({ path: `artifacts/portal-home-${test.info().project.name}.png`, fullPage: true });
  await page.getByRole('link', { name: /Class of 2027/ }).click();
  await expect(page.locator('.live-notice')).toBeVisible();
  await page.getByRole('navigation', { name: 'App', exact: true }).getByRole('link', { name: 'Company Procedures', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Company Procedures', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Contribute', exact: true }).click();
  await expect(page.getByLabel('Company', { exact: true })).toBeVisible();
  await page.getByRole('searchbox', { name: 'Find a company' }).fill('Barclays');
  await expect(page.getByLabel('Company', { exact: true }).getByRole('option', { name: /Barclays/ })).toContainText('2025');
  await expect(page.getByLabel('Company', { exact: true }).getByRole('option', { name: /Barclays/ })).toContainText('2027');
  await page.screenshot({ path: `artifacts/portal-contribute-${test.info().project.name}.png`, fullPage: true });
  await expect(page.getByRole('button', { name: 'Submit for review' })).toBeVisible();
  const appNav = page.getByRole('navigation', { name: 'App', exact: true });
  await expect(appNav.getByRole('link')).toHaveCount(2);
  await expect(appNav.getByRole('link', { name: 'Placement Stats', exact: true })).toBeVisible();
  await expect(appNav.getByRole('link', { name: /Alumni Contacts|My Contributions/ })).toHaveCount(0);
  await page.goto('/#2025/company/google');
  await expect(page.getByRole('heading', { name: 'Selected candidates', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Alumni contacts', exact: true })).toBeVisible();
  await expect(page.locator('.announcement-block').first()).toBeVisible();
  await page.getByRole('link', { name: 'My Account', exact: true }).click();
  await expect(page).toHaveURL(/#account$/);
  await expect(page.getByRole('heading', { name: 'My Account', exact: true })).toBeVisible();
  await expect(page.locator('.account-details')).toContainText('Test Student');
  await expect(page.locator('.account-details')).toContainText('@example.test');
  await expect(page.getByRole('heading', { name: 'My Contributions', exact: true })).toBeVisible();
  await expect(appNav.locator('[aria-current="page"]')).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `artifacts/portal-account-${test.info().project.name}.png`, fullPage: true });
  await page.reload();
  await expect(page.getByRole('heading', { name: 'My Account', exact: true })).toBeVisible();
  await page.goto('/#contributions');
  await expect(page).toHaveURL(/#account$/);
  await page.goto('/#alumni');
  await expect(page).toHaveURL(/#statistics$/);
  await expect(page.getByRole('heading', { name: 'Placement Stats', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'My Account', exact: true }).click();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Your placement prep/ })).toBeVisible();
  await page.goto('/#companies');
  await expect(page.getByRole('heading', { name: 'Good to see you.' })).toBeVisible();
  await expect(page.locator('.source-notes')).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('a cancelled Google popup leaves the login page usable', async ({ page }) => {
  await page.goto('/#login');
  const popupEvent = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Continue with Google' }).click();
  const popup = await popupEvent;
  await popup.waitForLoadState('domcontentloaded');
  await popup.close();
  await expect(page.getByRole('alert')).toContainText('Sign-in was cancelled', { timeout: 15000 });
  await expect(page.getByRole('button', { name: 'Continue with Google' })).toBeEnabled();
});
